# Generated by Django 3.2.10 on 2022-06-18 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeighbourHood',
        ),
    ]
